---
title: "p8105_hw1_xw2972"
author: "Xiwen Wu"
output: github_document
date: 2024-09-21
---

Problem:1
```{r}
data("penguins", package = "palmerpenguins")
# The variables include species island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g sex year.
# The data set has 344 rows and 8 columns.
mean(penguins$flipper_length_mm, na.rm = TRUE)
# The the mean flipper length is 200.9152.
library(tidyverse)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point()
ggsave("flipper_vs_bill_scatterplot.png")
```
Problem:2
```{r}
set.seed(123) 
random_sample <- rnorm(10)
logical_vector <- random_sample > 0
character_vector <- sample(letters, 10)
factor_vector <- factor(sample(c("Level 1", "Level 2", "Level 3"), 10, replace = TRUE))
df <- tibble(
  rs = random_sample,
  lv = logical_vector,
  cv = character_vector,
  fv = factor_vector
)
df %>% 
  pull(rs) %>% 
  mean()
df %>% 
  pull(lv) %>% 
  mean()
# I can get the mean for random_sample and logical_vector, cannot get it for character_vector and factor vector.
as.numeric(df$lv)
as.numeric(df$cv)
as.numeric(df$fv)
# For the character_vector, it returns NA with a warning saying that NAs introduced by coercion. The reason is that character cannot be converted to numerics, accordingly, it doesn't have a mean.
```

